In [1]:
 #Importing Libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
import requests
import csv
import pickle

In [2]:
#Connecting to drive
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

#Loading Data

In [95]:
path = '/content/drive/MyDrive/Projects/Weather Prediction/nuz_wr_1990_2020.csv'

In [96]:
df = pd.read_csv(path)

In [97]:
df.shape

(11542, 35)

In [98]:
df.head(100)

,Unnamed: 0.1,name,datetime,tempmax,tempmin,temp,feelslikemax,feelslikemin,feelslike,dew,...,uvindex,severerisk,sunrise,sunset,moonphase,conditions,description,icon,stations,Unnamed: 0
0,0,Nuzvid,1990-01-01,27.1,22.1,24.7,28.9,22.1,24.9,21.5,...,NaN,NaN,1990-01-01T06:35:40,1990-01-01T17:44:23,0.15,"Rain, Partially cloudy",Partly cloudy throughout the day with rain cle...,rain,43185099999,NaN
1,1,Nuzvid,1990-01-02,27.7,22.1,25.1,29.2,22.1,25.5,20.5,...,NaN,NaN,1990-01-02T06:36:01,1990-01-02T17:44:59,0.18,Partially cloudy,Partly cloudy throughout the day.,partly-cloudy-day,43185099999,NaN
2,2,Nuzvid,1990-01-03,27.7,21.1,24.6,29.4,21.1,25.1,20.3,...,NaN,NaN,1990-01-03T06:36:22,1990-01-03T17:45:34,0.22,Partially cloudy,Partly cloudy throughout the day.,partly-cloudy-day,43185099999,NaN
3,3,Nuzvid,1990-01-04,27.4,21.1,25.1,29.2,21.1,25.7,20.4,...,NaN,NaN,1990-01-04T06:36:41,1990-01-04T17:46:10,0.25,Clear,Clear conditions throughout the day.,clear-day,43185099999,NaN
4,4,Nuzvid,1990-01-05,27.7,21.2,24.6,29.0,21.2,24.9,18.7,...,NaN,NaN,1990-01-05T06:36:59,1990-01-05T17:46:47,0.29,Partially cloudy,Partly cloudy throughout the day.,partly-cloudy-day,43185099999,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,95,Nuzvid,1990-04-06,31.4,24.0,27.4,36.6,24.0,30.3,23.7,...,NaN,NaN,1990-04-06T05:58:00,1990-04-06T18:20:28,0.36,"Rain, Partially cloudy",Partly cloudy throughout the day with rain.,rain,"43185099999,43181099999",NaN
96,96,Nuzvid,1990-04-07,31.7,25.7,28.7,36.3,25.7,31.5,23.3,...,NaN,NaN,1990-04-07T05:57:15,1990-04-07T18:20:39,0.40,Partially cloudy,Partly cloudy throughout the day.,partly-cloudy-day,43185099999,NaN
97,97,Nuzvid,1990-04-08,32.4,24.7,28.6,38.0,24.7,32.1,23.9,...,NaN,NaN,1990-04-08T05:56:31,1990-04-08T18:20:50,0.43,Partially cloudy,Partly cloudy throughout the day.,partly-cloudy-day,43185099999,NaN
98,98,Nuzvid,1990-04-09,35.4,27.1,30.0,40.8,30.8,35.5,24.9,...,NaN,NaN,1990-04-09T05:55:46,1990-04-09T18:21:01,0.47,Partially cloudy,Partly cloudy throughout the day.,partly-cloudy-day,"43185099999,43181099999",NaN
99,99,Nuzvid,1990-04-10,33.7,26.7,29.4,41.7,26.7,35.0,25.7,...,NaN,NaN,1990-04-10T05:55:02,1990-04-10T18:21:12,0.50,Partially cloudy,Partly cloudy throughout the day.,partly-cloudy-day,43185099999,NaN

In [99]:
df.columns

Index(['Unnamed: 0.1', 'name', 'datetime', 'tempmax', 'tempmin', 'temp',
       'feelslikemax', 'feelslikemin', 'feelslike', 'dew', 'humidity',
       'precip', 'precipprob', 'precipcover', 'preciptype', 'snow',
       'snowdepth', 'windgust', 'windspeed', 'winddir', 'sealevelpressure',
       'cloudcover', 'visibility', 'solarradiation', 'solarenergy', 'uvindex',
       'severerisk', 'sunrise', 'sunset', 'moonphase', 'conditions',
       'description', 'icon', 'stations', 'Unnamed: 0'],
      dtype='object')

#Setting up data

In [100]:
df.isnull().sum()

Unnamed: 0.1            0
name                    0
datetime                0
tempmax                 6
tempmin                 6
temp                    6
feelslikemax            6
feelslikemin            6
feelslike               6
dew                     6
humidity                6
precip                  6
precipprob              6
precipcover             0
preciptype           7915
snow                 3901
snowdepth            3901
windgust            11388
windspeed               0
winddir                43
sealevelpressure       10
cloudcover              6
visibility             10
solarradiation       7310
solarenergy          7310
uvindex              7310
severerisk          11542
sunrise                 0
sunset                  0
moonphase               0
conditions              6
description             6
icon                    6
stations                6
Unnamed: 0           8406
dtype: int64

In [101]:
df = df.drop(['Unnamed: 0.1','name','windgust','severerisk','preciptype','snow','snowdepth','datetime','description','icon','solarradiation','solarenergy','uvindex','Unnamed: 0','stations','sunrise','sunset','moonphase'], axis=1)

In [102]:
df [df.isnull ().sum (axis=1) !=0]

,tempmax,tempmin,temp,feelslikemax,feelslikemin,feelslike,dew,humidity,precip,precipprob,precipcover,windspeed,winddir,sealevelpressure,cloudcover,visibility,conditions
147,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.00,0.0,NaN,NaN,NaN,NaN,NaN
148,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.00,0.0,NaN,NaN,NaN,NaN,NaN
499,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.00,0.0,NaN,NaN,NaN,NaN,NaN
1448,19.4,19.4,19.4,19.4,19.4,19.4,17.2,87.1,0.0,0.0,0.00,0.0,NaN,1015.8,10.0,4.0,Clear
1602,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.00,0.0,NaN,NaN,NaN,NaN,NaN
1913,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.00,0.0,NaN,NaN,NaN,NaN,NaN
2099,32.1,26.1,29.3,40.5,26.1,35.2,26.0,82.9,4.0,100.0,4.17,0.0,NaN,1006.4,70.6,7.4,"Rain, Partially cloudy"
2131,31.7,25.4,28.2,37.6,25.4,32.1,24.9,83.3,0.0,0.0,0.00,0.0,NaN,1007.9,35.0,5.5,Partially cloudy
2141,30.1,26.1,28.1,36.1,26.1,32.3,25.5,86.6,0.0,0.0,0.00,0.0,NaN,1010.1,22.5,5.5,Partially cloudy
3141,31.1,26.4,28.7,37.0,26.4,32.6,24.7,79.6,0.0,0.0,0.00,0.0,NaN,1002.9,97.5,7.0,Overcast
3150,24.1,24.1,24.1,24.1,24.1,24.1,22.6,91.3,6.0,100.0,4.17,0.0,NaN,1007.9,40.0,4.0,"Rain, Partially cloudy"
3166,29.9,24.4,28.0,38.4,24.4,33.8,26.3,90.9,13.8,100.0,8.33,0.0,NaN,1005.9,90.0,7.0,"Rain, Partially cloudy"
3250,29.1,24.4,26.7,33.5,24.4,28.2,23.3,82.1,0.0,0.0,0.00,0.0,NaN,1011.9,63.3,6.0,Partially cloudy
3297,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.00,0.0,NaN,NaN,NaN,NaN,NaN
3316,28.2,21.9,24.9,30.1,21.9,25.4,20.6,80.1,0.0,0.0,0.00,0.0,NaN,1010.9,18.6,6.6,Clear
3337,29.4,21.9,26.0,32.5,21.9,27.1,22.4,82.7,0.0,0.0,0.00,0.0,NaN,1013.4,26.3,6.6,Partially cloudy
3579,33.1,25.7,29.7,41.4,25.7,34.8,25.2,78.3,0.0,0.0,0.00,0.0,NaN,1004.9,40.0,6.3,Partially cloudy
3586,30.1,26.2,28.4,36.1,26.2,33.2,25.5,84.6,9.0,100.0,12.50,0.0,NaN,1008.5,58.6,7.4,"Rain, Partially cloudy"
3605,31.4,19.1,25.7,31.1,19.1,25.9,18.1,65.9,0.0,0.0,0.00,0.0,NaN,1013.9,7.1,7.4,Clear
3607,30.4,19.7,25.7,30.6,19.7,25.9,18.6,67.8,0.0,0.0,0.00,0.0,NaN,1014.1,2.9,6.6,Clear
3617,29.2,21.1,25.5,31.6,21.1,26.1,21.1,77.6,0.0,0.0,0.00,0.0,NaN,1010.7,30.0,6.6,Partially cloudy
3623,30.9,20.4,24.9,32.2,20.4,25.2,20.1,76.7,0.0,0.0,0.00,0.0,NaN,1014.6,12.0,5.2,Clear
3631,30.1,19.9,24.3,30.2,19.9,24.5,17.8,69.4,0.0,0.0,0.00,0.0,NaN,1012.5,3.8,6.3,Clear
3911,35.1,28.1,30.6,43.6,33.4,36.9,25.1,73.5,0.0,0.0,0.00,0.0,NaN,1004.7,60.0,5.5,Partially cloudy
3930,31.4,26.2,28.8,37.8,26.2,33.6,25.2,81.2,0.0,0.0,0.00,0.0,NaN,1008.3,65.7,6.6,Partially cloudy
3940,33.7,26.1,30.1,42.3,26.1,36.0,25.3,76.1,1.4,100.0,8.33,0.0,NaN,1005.8,88.6,6.6,"Rain, Partially cloudy"
3949,32.4,26.9,29.2,41.4,31.1,35.3,25.9,83.1,0.0,0.0,0.00,0.0,NaN,1007.5,42.5,6.3,Partially cloudy
3950,31.9,25.2,28.2,37.9,25.2,31.2,24.4,81.0,0.0,0.0,0.00,0.0,NaN,1007.9,7.5,5.8,Clear
3951,34.2,24.1,28.8,40.0,24.1,31.8,23.8,76.3,0.0,0.0,0.00,0.0,NaN,1008.5,17.1,6.6,Clear
3952,33.9,22.4,27.9,39.8,22.4,29.9,22.4,66.9,0.0,0.0,0.00,0.0,NaN,1009.3,1.3,5.5,Clear
4057,34.2,20.2,26.2,50.1,20.2,28.6,21.3,76.8,0.0,0.0,0.00,0.0,NaN,1010.5,1.3,5.3,Clear
4173,33.1,27.9,29.6,41.2,31.9,36.0,25.6,79.5,2.9,100.0,16.67,0.0,NaN,1004.5,91.3,4.0,"Rain, Overcast"
4305,31.1,24.9,27.7,38.7,24.9,31.2,25.4,87.9,44.0,100.0,16.67,0.0,NaN,1007.4,88.8,3.8,"Rain, Partially cloudy"
4319,31.2,25.9,28.1,37.6,25.9,31.6,24.9,83.3,0.4,100.0,16.67,0.0,NaN,1009.3,67.1,3.7,"Rain, Partially cloudy"
4320,33.1,25.1,28.4,37.4,25.1,31.1,23.9,78.4,0.3,100.0,12.50,0.0,NaN,1009.0,26.3,5.5,"Rain, Partially cloudy"
4352,30.1,21.4,25.9,33.9,21.4,26.9,21.0,75.1,0.0,0.0,0.00,0.0,NaN,1012.0,27.5,4.0,Partially cloudy
4398,28.7,19.4,23.7,29.9,19.4,24.1,19.2,77.6,0.0,0.0,0.00,0.0,NaN,1011.8,10.0,4.0,Clear
4669,30.2,25.1,27.9,37.8,25.1,32.0,25.1,84.9,0.0,0.0,0.00,0.0,NaN,1008.9,81.4,4.0,Partially cloudy
4673,28.4,23.9,26.5,34.0,23.9,28.9,24.9,91.4,61.5,100.0,12.50,0.0,NaN,1007.6,87.5,4.0,"Rain, Partially cloudy"
4685,27.7,23.9,25.9,31.5,23.9,27.3,23.6,87.0,0.0,0.0,0.00,0.0,NaN,1010.0,88.8,4.0,Partially cloudy
4717,29.2,21.1,25.4,33.1,21.1,26.8,22.2,83.1,0.0,0.0,0.00,0.0,NaN,1013.9,27.1,3.7,Partially cloudy
4739,29.7,20.1,24.3,30.6,20.1,25.0,19.7,78.1,0.0,0.0,0.00,0.0,NaN,1012.0,27.1,3.4,Partially cloudy
5018,27.9,25.4,27.0,32.8,25.4,30.3,25.6,91.8,18.0,100.0,4.17,0.0,NaN,1006.0,86.3,4.0,"Rain, Partially cloudy"
7834,35.0,27.0,30.4,39.6,30.9,35.1,24.2,71.6,7.0,100.0,62.50,20.5,218.9,NaN,84.5,NaN,"Rain, Partially cloudy"
7835,36.1,26.6,30.6,39.9,26.6,34.5,23.2,67.0,1.6,100.0,25.00,22.0,234.3,NaN,89.4,NaN,"Rain, Partially cloudy"
7836,33.5,26.5,29.7,36.1,26.5,32.6,22.4,66.4,0.0,0.0,0.00,24.1,262.9,NaN,90.2,NaN,Overcast
7837,36.8,26.0,31.1,38.9,26.0,33.0,20.7,56.7,0.0,0.0,0.00,28.1,265.1,NaN,71.2,NaN,Partially cloudy

In [103]:
df = df.dropna()

In [104]:
df [df.isnull ().sum (axis=1) !=0]

Empty DataFrame
Columns: [tempmax, tempmin, temp, feelslikemax, feelslikemin, feelslike, dew, humidity, precip, precipprob, precipcover, windspeed, winddir, sealevelpressure, cloudcover, visibility, conditions]
Index: []

In [105]:
print(df.shape)
df.head()

(11495, 17)

,tempmax,tempmin,temp,feelslikemax,feelslikemin,feelslike,dew,humidity,precip,precipprob,precipcover,windspeed,winddir,sealevelpressure,cloudcover,visibility,conditions
0,27.1,22.1,24.7,28.9,22.1,24.9,21.5,83.0,0.3,100.0,4.17,11.2,51.2,1012.5,58.8,7.0,"Rain, Partially cloudy"
1,27.7,22.1,25.1,29.2,22.1,25.5,20.5,76.5,0.0,0.0,0.00,9.4,73.7,1013.2,28.8,7.0,Partially cloudy
2,27.7,21.1,24.6,29.4,21.1,25.1,20.3,77.8,0.0,0.0,0.00,14.8,75.7,1014.5,25.7,7.4,Partially cloudy
3,27.4,21.1,25.1,29.2,21.1,25.7,20.4,76.1,0.0,0.0,0.00,14.8,83.9,1015.8,10.0,7.0,Clear
4,27.7,21.2,24.6,29.0,21.2,24.9,18.7,71.4,0.0,0.0,0.00,22.3,68.9,1016.6,37.1,6.1,Partially cloudy

#Balancing the Data & Labelling

In [106]:
df['conditions'].value_counts()

Partially cloudy          6110
Rain, Partially cloudy    2635
Clear                     1578
Rain, Overcast             970
Overcast                   193
Rain                         9
Name: conditions, dtype: int64

In [107]:
from sklearn.utils import resample

#Separate majority and minority classes
df_upsampled = df[df['conditions'] == 'Partially cloudy']
for con in ['Rain, Partially cloudy','Clear','Rain, Overcast','Overcast','Rain']:
  df_minority = df[df['conditions'] == con]

# Upsample minority class and other classes separately
# If not, random samples from combined classes will be duplicated and we run into
#same issue as before, undersampled remians undersampled.
  df_minority_upsampled = resample(df_minority, 
                                 replace=True,     # sample with replacement
                                 n_samples=6110,    # to match average class
                                 random_state=42) # reproducible results
 

# Combine majority class with upsampled minority class
  df_upsampled = pd.concat([df_upsampled, df_minority_upsampled])

In [108]:
df_upsampled['conditions'].value_counts()

Partially cloudy          6110
Rain, Partially cloudy    6110
Clear                     6110
Rain, Overcast            6110
Overcast                  6110
Rain                      6110
Name: conditions, dtype: int64

In [109]:
X_ = df_upsampled.drop('conditions',axis = 1)
Y_con = df_upsampled['conditions']

In [110]:
from sklearn.preprocessing import LabelEncoder

# Create a LabelEncoder 
le = LabelEncoder()
le.fit(Y_con)

Y_con = le.transform(Y_con)

In [132]:
con = dict(zip(le.classes_, le.transform(le.classes_)))
con

{'Clear': 0,
 'Overcast': 1,
 'Partially cloudy': 2,
 'Rain': 3,
 'Rain, Overcast': 4,
 'Rain, Partially cloudy': 5}

In [111]:
from sklearn.model_selection import train_test_split
xtrain_con,xtest_con,ytrain_con,ytest_con= train_test_split(X_,Y_con,random_state=0,test_size = 0.3)

#Model for condition: RandomForestClassifier

In [122]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

In [123]:
model = RandomForestClassifier(n_estimators = 55)

In [124]:
res = model.fit(xtrain_con,ytrain_con)

In [125]:
yp_con = model.predict(xtrain_con) 
accuracy1 = accuracy_score(yp_con,ytrain_con)
print('Train accuracy: ',accuracy1)

Train accuracy:  1.0

In [127]:
yp_con = model.predict(xtest_con) 
accuracy2 = accuracy_score(yp_con,ytest_con)
print('Test accuracy: ',accuracy2)

Test accuracy:  1.0

In [128]:
pickle.dump(model, open('con_model.pkl', 'wb'))

#Deploying the model

In [ ]:
!pip install gradio
import pickle
import gradio as gr

In [134]:
from datetime import datetime
dateTime = datetime.now()
if dateTime.month<10:
  month = '0'+str(dateTime.month)
else:
  month = str(dateTime.month)
if dateTime.day<10:
  day = '0'+str(dateTime.day)
else:
  day = str(dateTime.day)
today = str(dateTime.year)+'-'+month+'-'+ day
today

'2023-04-26'

In [152]:
class Weather_pred:
  def __init__(self):
    self.data = None
    self.condition = None
    self.true_con = None
    self.true_des = None
    self.con_model = pickle.load(open('/content/drive/MyDrive/Projects/Weather Prediction/con_model.pkl', 'rb'))

  def get_data(self,Place,Date):
    req = "https://weather.visualcrossing.com/VisualCrossingWebServices/rest/services/timeline/" + Place + '/' + Date + '/' + Date + "?unitGroup=metric&include=days&key=J6J2CBFC25RTZ9CGFZTWYCQBD&contentType=csv"
    response = requests.request("GET", req)
    self.data = pd.DataFrame(csv.reader(response.text.splitlines(), delimiter=',',quotechar='"'))
  def show_data(self):
    print(self.data)
  
  def preprocess(self):
    input = self.data.drop(0)
    self.true_con = input[29][1]
    self.true_des = input[30][1]
    input = input.drop([31,32,26,27,28,30,29,0,1,13,14,22,23,24,25,15,16],axis=1)
    return input

  def predict(self,Place = 'nuzvid',Date = today):
    self.get_data(Place,Date)
    X = self.preprocess()
    con_out = self.con_model.predict(X)
    con = {'Clear': 0, 'Overcast': 1, 'Partially cloudy': 2, 'Rain': 3, 'Rain, Overcast': 4, 'Rain, Partially cloudy': 5}

    for key,values in con.items():
      if values== con_out:
        self.condition = key
        out1 = "Prediction: "+self.condition+"\nTruth: "+self.true_con
    out2 = self.true_des
    return out1,out2

In [153]:
wp = Weather_pred()

#Gradio Interface

In [149]:
input1 = gr.Textbox(placeholder = 'YYYY-MM-DD')
output1 = gr.Textbox(label='Condition:')
output2 = gr.Textbox(label='Description:')

In [155]:
demo = gr.Interface(fn=wp.predict, inputs=['text',input1], outputs=[output1,output2])
demo.launch(share = True,inline=True)

Colab notebook detected. To show errors in colab notebook, set debug=True in launch()
Running on public URL: https://fd3465bc67b7297c30.gradio.live

This share link expires in 72 hours. For free permanent hosting and GPU upgrades (NEW!), check out Spaces: https://huggingface.co/spaces